[package]
name = "gmae"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO remove dynamic before release
bevy = { version = "0.7.0", features = ["dynamic"] }
bevy-inspector-egui = "0.10.0"
bevy_mod_debugdump = "0.4.0"
image = "0.23.14" # to generate textures in memory
convert_case = "0.5.0" # to convert MaterialName to file_name
pad = "0.1.6"
rand = "0.8.4" #for random color textures in debug
flate2 = "1.0" #for reading lvls
serde_json = "1.0.79" #for reading lvls
once_cell = "1.10.0"
bevy_egui = "0.13.0"
bevy_kira_audio = { version = "0.9.0", features = ["mp3"] }

[dependencies.lib]
version = "0.0.0"
path = "./lib"

[build-dependencies]
fastnbt = "1" #for reading mc world
fastanvil = "0.24.0" #for reading mc world
serde_json = "1.0.79" #for serializing lvls
flate2 = "1.0" #for serializing lvls

[build-dependencies.lib]
version = "0.0.0"
path = "./lib"