[package]
name = "gmae"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO remove dynamic before release
bevy = { version = "0.6.0", features = ["dynamic"] }
bevy_fly_camera = "0.8.0"
fastnbt = "1"
fastanvil="0.24.0"