name: CI

on:
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always
    RUST_TOOLCHAIN: nightly

jobs:
    lints:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v2

            -   name: Cache
                uses: Swatinem/rust-cache@v1

            -   name: rust-clippy-check
                uses: actions-rs/clippy-check@v1.0.7