name: CI

on:
    pull_request:
        branches: [ master ]

jobs:
    lints:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v2

            -   uses: actions-rs/toolchain@v1
                with:
                    toolchain: nightly
                    components: clippy
                    override: true
            -   uses: actions-rs/clippy-check@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    args: --all-features